apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-svc
  namespace: {{ .Values.project }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.containerport }}
      protocol: TCP
      name: http
  selector:
    project: {{ .Values.project }}
    app: {{ .Values.app }}
    tier: front-end