import TemplateForgetPassword from './TemplateForgatePassword/TemplateForgetPassword';
import TemplateResetPassword from './TemplateResetPassword/TemplateResetPassword';
import TemplateSendMail from './TemplateSendMail/TemplateSendMail';
import TemplateLogin from './TemplateLogin/TemplateLogin';
import TemplateChangePassword from './TemplateChangePassword/TemplateChangePassword';
import TemplateProfileModal from './TemplateProfileModal/TemplateProfileModal';
import TemplateUser from './TemplateUser/TemplateUser';
import TemplateGroup from './TemplateGroup/TemplateGroup';
import TemplateLot from './TemplateLot/TemplateLot';
import TemplateDocument from './TemplateDocument/TemplateDocument';
import TemplateCgu from './TemplateCgu/TemplateCgu';
import TemplateConfidentiality from './TemplateConfidentiality/TemplateConfidentiality';
export const ForgertPasswordTemplate = TemplateForgetPassword;
export const ResetPasswordTemplate = TemplateResetPassword;
export const SendMailTemplate = TemplateSendMail;
export const LoginTemplate = TemplateLogin;
export const ChangePasswordTemplate = TemplateChangePassword;
export const ProfileModalTemplate = TemplateProfileModal;
export const UserTemplate = TemplateUser;
export const GroupTemplate = TemplateGroup;
export const LotTemplate = TemplateLot;
export const DocumentTemplate = TemplateDocument;
export const CguTemplate = TemplateCgu;
export const ConfidentialityTemplate = TemplateConfidentiality;
