import AtomButton from './AtomButton/AtomButton.js';
import AtomText from './AtomText/AtomText.js';
import AtomDatePicker from './AtomDatePicker/AtomDatePicker';
import AtomProgressBar from './AtomProgressBar/AtomProgressBar';
import AtomAutoComplete from './AtomAutoComplete/AtomAutoComplete';
import AtomItemDropDown from './AtomItemDropDown/AtomItemDropDown';
import AtomItemPagination from './AtomItemPagination/AtomItemPagination';
import AtomIcon from './AtomIcon/AtomIcon';
import AtomImg from './AtomImg/AtomImg';
import AtomTdTable from './AtomTdTable/AtomTdTable';
import AtomInput from './AtomInput/AtomInput';
import AtomLoader from './AtomLoader/AtomLoader.js';

export const Icon = AtomIcon;
export const Button = AtomButton;
export const Text = AtomText;
export const DatePicker = AtomDatePicker;
export const ProgressBar = AtomProgressBar;
export const AutoComplete = AtomAutoComplete;
export const ItemDropDown = AtomItemDropDown;
export const ItemPagination = AtomItemPagination;
export const Img = AtomImg;
export const TdTable = AtomTdTable;
export const Input = AtomInput;
export const Loader = AtomLoader;
