import OrganismInfo from './OrganismInfo/OrganismInfo';
import OrganismGestionDroit from './OrganismGestionDroit/OrganismGestionDroit';
import OrganismDroitAdmin from './OrganismDroitAdmin/OrganismDroitAdmin';
import OrganismForgetPasswordCard from './OrganismForgetPasswordCard/OrganismForgetPasswordCard';
import OrganismSendMailCard from './OrganismSendMailCard/OrganismSendMailCard';
import OrganismResetPasswordCard from './OrganismResetPasswordCard/OrganismResetPasswordCard';
import OrganismHeader from './OrganismHeader/OrganismHeader';
import OrganismAlertModal from './OrganismAlertModal/OrganismAlertModal';
import OrganismLogin from './OrganismLogin/OrganismLogin.js';
import OrganismEditor from './OrganismEditor/OrganismEditor.js';
import OrganismChangePassword from './OrganismChangePassword/OrganismChangePassword.js';
import OrganismSideBar from './OrganismSideBar/OrganismSideBar';
import OrganismTableUser from './OrganismTableUser/OrganismTableUser';
import OrganismTableGroup from './OrganismTableGroup/OrganismTableGroup';
import OrganismTableLot from './OrganismTableLot/OrganismTableLot';
import OrganismModalEditSubCategory from './OrganismModalEditSubCategory/OrganismModalEditSubCategory';
import OrganismModalCropImage from './OrganismModalCropImage/OrganismModalCropImage';
import OrganismModalValidateDelete from './OrganismModalValidateDelete/OrganismModalValidateDelete';
import OrganismGroupSousGroupModal from './OrganismGroupSousGroupModal/OrganismGroupSousGroupModal';
import OrganismModalDetail from './OrganismModalDetail/OrganismModalDetail';
import OrganismModalInfo from './OrganismModalInfo/OrganismModalInfo';
import OrganismModalModifySubCategory from './OrganismModalModifySubCategory/OrganismModalModifySubCategory';
import OrganismTableDocument from './OrganismTableDocument/OrganismTableDocument';
import OrganismModalDescriptionWithInput from './OrganismModalDescriptionWithInput/OrganismModalDescriptionWithInput';
export const ForgetPasswordOrganism = OrganismForgetPasswordCard;
export const SendMailCardOrganism = OrganismSendMailCard;
export const ResetPasswordCardOrganism = OrganismResetPasswordCard;
export const LoginOrganism = OrganismLogin;
export const EditorOrganism = OrganismEditor;
export const ChangePasswordOrganism = OrganismChangePassword;
export const HeaderOrganism = OrganismHeader;
export const AlertModalOrganism = OrganismAlertModal;
export const SideBarOrganism = OrganismSideBar;
export const InfoOrganism = OrganismInfo;
export const GestionDroitOrganism = OrganismGestionDroit;
export const DroitAdminOrganism = OrganismDroitAdmin;
export const TableUserOrganism = OrganismTableUser;
export const TableGroupOrganism = OrganismTableGroup;
export const TableLotOrganism = OrganismTableLot;
export const ModalEditSubCategory = OrganismModalEditSubCategory;
export const ModalCropImage = OrganismModalCropImage;
export const ModalValidateDelete = OrganismModalValidateDelete;
export const ModalGroupSousGroupOrganism = OrganismGroupSousGroupModal;
export const ModalDetailOrganism = OrganismModalDetail;
export const ModalInfoOrganism = OrganismModalInfo;
export const ModalModifySubCategory = OrganismModalModifySubCategory;
export const TableDocumentOrganism = OrganismTableDocument;
export const ModalDescriptionWithInputOrganism = OrganismModalDescriptionWithInput;
