name: ci-pull-request

on: 
  pull_request:    
    branches:
      - main
      - dev
      
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: node:14.17-alpine3.10
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm test
      - run: npm run build