name: deploy-dev

on: 
  push:    
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: node:14.17-alpine3.10
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run test
      - run: npm run build
  push_to_registry:
    name: Push Docker image to Azure Registry
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: check out the repo 
        uses: actions/checkout@v2
        
      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1
        
      - name: log into Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: deadpoolcr.azurecr.io
          username: ${{ secrets.OWNER }}
          password: ${{ secrets.TOKEN }}
          
      - name: push to Azure Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            API_URL=https://dev.api.start.deadpool.ovh/
            CGU_URL=https://dev.landing.start.deadpool.ovh/
          tags: |
            deadpoolcr.azurecr.io/start-admin-dev:${{ github.sha }}
            deadpoolcr.azurecr.io/start-admin-dev:latest

  helm:
      runs-on: ubuntu-latest
      needs: push_to_registry
      steps:
        - uses: actions/checkout@v2
        - uses: azure/k8s-bake@v1
          with:
            renderEngine: 'helm'
            helmChart: './helm/' 
            overrides: |
              image.tag:${{ github.sha }}
              project:start
              app:admin
              repo:dev
              containerport:80
              host:dev.admin.start.deadpool.ovh
            helm-version: 'latest' 
          id: bake
        - uses: actions/upload-artifact@main
          with:
            name: helm_artifact
            path: ${{ steps.bake.outputs.manifestsBundle }}
  deploy:
      runs-on: ubuntu-20.04
      needs: helm
      steps:
        - uses: Azure/k8s-set-context@v1
          with:
            kubeconfig: ${{ secrets.DEVKUBE }}
        - uses: actions/download-artifact@main
          with:
            name: helm_artifact
            path: k8s
        - uses: Azure/k8s-deploy@v1.4
          with:
            namespace: 'start'
            manifests: k8s/*
            kubectl-version: 'latest'
